CREATE TABLE "movies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "description" text NOT NULL,
  "image" text,
  "rating" float,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp
);

CREATE INDEX ON "movies" ("title");
