// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	AddMovie(ctx context.Context, arg AddMovieParams) (Movie, error)
	DeleteMovie(ctx context.Context, id int32) error
	DetailMovie(ctx context.Context, id int32) (Movie, error)
	ListMovies(ctx context.Context, limit int32) ([]Movie, error)
	ListMoviesByTitle(ctx context.Context, arg ListMoviesByTitleParams) ([]Movie, error)
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error)
}

var _ Querier = (*Queries)(nil)
